name: CI

on:
  workflow_dispatch:  # 添加这一行就可以手动触发
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Generate Astro types
        run: npx astro sync
      - name: Build
        run: npm run build
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          SOURCE: "./dist/"           # 本地构建目录
          TARGET: "/www/wwwroot/blog.parligerly.com"    # 服务器上的目标路径（请根据实际修改）
          ARGS: "-avzr --delete"      # 参数含义：归档、压缩、递归、删除目标多余文件
